/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppDoctorRouteImport } from './routes/_app/doctor'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAppointmentsRouteImport } from './routes/_app/appointments'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppScansIndexRouteImport } from './routes/_app/scans/index'
import { Route as AppScansNewRouteImport } from './routes/_app/scans/new'
import { Route as AppScansScanIdRouteImport } from './routes/_app/scans/$scanId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorRoute = AppDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppScansIndexRoute = AppScansIndexRouteImport.update({
  id: '/scans/',
  path: '/scans/',
  getParentRoute: () => AppRoute,
} as any)
const AppScansNewRoute = AppScansNewRouteImport.update({
  id: '/scans/new',
  path: '/scans/new',
  getParentRoute: () => AppRoute,
} as any)
const AppScansScanIdRoute = AppScansScanIdRouteImport.update({
  id: '/scans/$scanId',
  path: '/scans/$scanId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/appointments': typeof AppAppointmentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/doctor': typeof AppDoctorRoute
  '/messages': typeof AppMessagesRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/scans/$scanId': typeof AppScansScanIdRoute
  '/scans/new': typeof AppScansNewRoute
  '/scans/': typeof AppScansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/appointments': typeof AppAppointmentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/doctor': typeof AppDoctorRoute
  '/messages': typeof AppMessagesRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/scans/$scanId': typeof AppScansScanIdRoute
  '/scans/new': typeof AppScansNewRoute
  '/scans': typeof AppScansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/doctor': typeof AppDoctorRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/scans/$scanId': typeof AppScansScanIdRoute
  '/_app/scans/new': typeof AppScansNewRoute
  '/_app/scans/': typeof AppScansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/appointments'
    | '/dashboard'
    | '/doctor'
    | '/messages'
    | '/profile'
    | '/settings'
    | '/scans/$scanId'
    | '/scans/new'
    | '/scans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/appointments'
    | '/dashboard'
    | '/doctor'
    | '/messages'
    | '/profile'
    | '/settings'
    | '/scans/$scanId'
    | '/scans/new'
    | '/scans'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/appointments'
    | '/_app/dashboard'
    | '/_app/doctor'
    | '/_app/messages'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/scans/$scanId'
    | '/_app/scans/new'
    | '/_app/scans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor': {
      id: '/_app/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AppDoctorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scans/': {
      id: '/_app/scans/'
      path: '/scans'
      fullPath: '/scans/'
      preLoaderRoute: typeof AppScansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scans/new': {
      id: '/_app/scans/new'
      path: '/scans/new'
      fullPath: '/scans/new'
      preLoaderRoute: typeof AppScansNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scans/$scanId': {
      id: '/_app/scans/$scanId'
      path: '/scans/$scanId'
      fullPath: '/scans/$scanId'
      preLoaderRoute: typeof AppScansScanIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDoctorRoute: typeof AppDoctorRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppScansScanIdRoute: typeof AppScansScanIdRoute
  AppScansNewRoute: typeof AppScansNewRoute
  AppScansIndexRoute: typeof AppScansIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDoctorRoute: AppDoctorRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppScansScanIdRoute: AppScansScanIdRoute,
  AppScansNewRoute: AppScansNewRoute,
  AppScansIndexRoute: AppScansIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
